language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.cache"
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: CPcTztCgPGz5QCI/GUX2WZKPayV5X0gH+LK+hX711oW9agjdyqd0RijDuDVMEhcMQSqUl8cvDZNPPeDIDHBQfCjKxdavizqHe9R+W1LGeI7F4d5AMdX1G4TmNtKk8G+p7zpS2M3NlDOepqxEBqlpa1pnggmq7p0YyY7bJBAxx0LuTIyQz+Hl8PLt7r0QyvWtlGM5vTnFocHWMW+CVsB/aZm5fNu70y4SzxBOVpnpWmjGpyAvow4CjgFR4JrSi/A7FS6Nz/f1tsS81NRzE7KtO49HXB0X221EwWhin+PCYok3/YbFsU787dk12cCn9G1gB81csFxdD5o3xGxxVx56UoyXSitF3i5wVs4XLotf0eDcnDtUcuqeh23Nvv8GecanpS+kzNgxfU6Gu3upNq9s9hWKTpRsQNm4IhVjG2tMNuDdmIiEmRbZmZkHWhpRxcIM+jkq7zdfOsKXgtyAIhW5LYRmd419T1mP8vRL2ovuQFzyHq4BQGWFxGmK6EUgEBWMIELMo3wS9iaPDlAYaiJsLSvxQOctfzEABm3taiENiKVzdOt/qeZuJL0eQYHX27sK4G9yrVEzMKN8Z6ncPWl6o/V6ee6gFg4rgLWzuLp0O+CJ6645t28PqzgDNL2iz+t3EcsL1Ivmr2P2a8xSqR6vCAvfl6tE1CSxl7uzc6AFlVY=
  app: frozen-everglades-34657
  on:
    repo: kcin1018/fem-ember-commently
